# Generated by Django 6.0.4 on 2026-04-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='VehicleRent Pro', max_length=200)),
                ('tagline', models.CharField(blank=True, default='The Digital Concierge', max_length=300)),
                ('logo', models.ImageField(blank=True, help_text='Site logo image', upload_to='site/')),
                ('favicon', models.ImageField(blank=True, upload_to='site/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Without + sign, e.g. 919999999999', max_length=20)),
                ('whatsapp_default_message', models.CharField(blank=True, default="Hi, I'm interested in renting a vehicle from your fleet.", max_length=500)),
                ('google_maps_embed', models.TextField(blank=True, help_text='Google Maps embed iframe URL')),
                ('hero_title', models.CharField(default='Rent Your Perfect Vehicle', max_length=300)),
                ('hero_subtitle', models.CharField(blank=True, default='Premium Vehicle Rental', max_length=500)),
                ('hero_cta_text', models.CharField(default='Browse Fleet', max_length=100)),
                ('hero_image', models.ImageField(blank=True, help_text='Hero background/side image', upload_to='site/hero/')),
                ('about_title', models.CharField(default='About Us', max_length=300)),
                ('about_content', models.TextField(blank=True, help_text='Main about page content (HTML allowed)')),
                ('about_image', models.ImageField(blank=True, upload_to='site/about/')),
                ('about_mission', models.TextField(blank=True, help_text='Our Mission statement')),
                ('about_vision', models.TextField(blank=True, help_text='Our Vision statement')),
                ('years_in_business', models.PositiveIntegerField(blank=True, default=0)),
                ('total_happy_customers', models.PositiveIntegerField(blank=True, default=0)),
                ('license_number', models.CharField(blank=True, help_text='Business license/registration number', max_length=200)),
                ('license_details', models.TextField(blank=True, help_text='License details, certifications, registrations (HTML allowed)')),
                ('meta_title', models.CharField(blank=True, help_text='Default page title for SEO', max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('og_image', models.ImageField(blank=True, help_text='Default Open Graph sharing image', upload_to='site/seo/')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, default='Premium vehicle rental service. Flexible daily, weekly & monthly plans.', max_length=500)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, help_text='e.g. Business Owner, Tourist', max_length=200)),
                ('quote', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/')),
                ('rating', models.PositiveIntegerField(default=5, help_text='1-5 stars')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Site Settings (Legacy)'},
        ),
    ]
