# Generated by Django 5.0.1 on 2026-04-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_testimonial_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='show_brand_name',
            field=models.BooleanField(default=True, help_text='Show brand name text next to the logo'),
        ),
    ]
