# Generated by Django 5.0.1 on 2026-04-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_show_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_bg_1',
            field=models.ImageField(blank=True, help_text='Hero background slide 1', upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_bg_2',
            field=models.ImageField(blank=True, help_text='Hero background slide 2', upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_bg_3',
            field=models.ImageField(blank=True, help_text='Hero background slide 3', upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_description',
            field=models.CharField(blank=True, default='Explore our premium fleet. Flexible daily, weekly, and monthly rentals with 24/7 roadside support.', max_length=500),
        ),
    ]
