# Generated by Django 6.0.4 on 2026-10-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_hero_bg_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='theme',
            field=models.CharField(choices=[('editorial', 'Editorial'), ('night', 'Night Drive'), ('route', 'Kerala Route'), ('reels', 'Showroom Reels'), ('bento', 'Bento Concierge')], default='editorial', help_text='Design of the public website', max_length=20),
        ),
    ]
