# Generated by Django 6.0.4 on 2026-10-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfig_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_highlights',
            field=models.TextField(blank=True, default='Well-maintained vehicles\nFlexible rental plans\nTrusted local support', help_text='Short trust points under the hero button, one per line (up to 3)'),
        ),
    ]
