# Generated by Django 6.0.4 on 2026-05-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='drop_city',
            field=models.CharField(blank=True, help_text='City slug from booking widget', max_length=120),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='pickup_city',
            field=models.CharField(blank=True, help_text='City slug from booking widget', max_length=120),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='rental_type',
            field=models.CharField(blank=True, choices=[('self_drive', 'Self-Drive'), ('with_driver', 'With Driver')], max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='requested_addons',
            field=models.JSONField(blank=True, default=list, help_text='List of addon slugs requested'),
        ),
    ]
