# Generated by Django 6.0.4 on 2026-04-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('id_proof_type', models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar'), ('driving_license', 'Driving License'), ('passport', 'Passport'), ('voter_id', 'Voter ID')], max_length=50)),
                ('id_proof_number', models.CharField(blank=True, max_length=100)),
                ('id_proof_image', models.ImageField(blank=True, upload_to='customers/id_proofs/')),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('license_image', models.ImageField(blank=True, upload_to='customers/licenses/')),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
