# Generated by Django 6.0.4 on 2026-10-09 04:55

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_proof_image',
            field=models.ImageField(blank=True, upload_to=customers.models.upload_id_proofs),
        ),
        migrations.AlterField(
            model_name='customer',
            name='license_image',
            field=models.ImageField(blank=True, upload_to=customers.models.upload_licenses),
        ),
    ]
