# Generated by Django 6.0.4 on 2026-04-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='battery_capacity_kwh',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Battery capacity in kWh (for EV/Hybrid)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='charging_time_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Charging time in hours (for EV)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fast_charging',
            field=models.BooleanField(default=False, help_text='Supports fast charging'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='motor_power_kw',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Motor power in kW (for EV/Hybrid)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='range_km',
            field=models.PositiveIntegerField(blank=True, help_text='Range in km on full charge (for EV/Hybrid)', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_cc',
            field=models.PositiveIntegerField(blank=True, help_text='For petrol/diesel/CNG vehicles', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage_kmpl',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='For petrol/diesel vehicles', max_digits=5, null=True),
        ),
    ]
