# Generated by Django 6.0.4 on 2026-04-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_battery_capacity_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='minimum_rental_days',
            field=models.PositiveIntegerField(default=1, help_text='Minimum rental period in days'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rental_mode',
            field=models.CharField(choices=[('daily', 'Daily Rental'), ('weekly', 'Weekly Rental'), ('monthly', 'Monthly Rental'), ('flexible', 'Flexible (All Plans)')], default='flexible', help_text='How this vehicle is rented out', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
