# Generated by Django 5.0.1 on 2026-04-13 04:20

from django.db import migrations


def add_categories(apps, schema_editor):
    VehicleCategory = apps.get_model("vehicles", "VehicleCategory")
    categories = [
        {
            "name": "Wedding Service",
            "slug": "wedding-service",
            "description": "Luxury vehicles for wedding occasions",
            "icon": "favorite",
            "display_order": 7,
        },
        {
            "name": "Premium Cars",
            "slug": "premium-cars",
            "description": "Premium and luxury car collection",
            "icon": "star",
            "display_order": 8,
        },
    ]
    for cat in categories:
        VehicleCategory.objects.get_or_create(name=cat["name"], defaults=cat)


def remove_categories(apps, schema_editor):
    VehicleCategory = apps.get_model("vehicles", "VehicleCategory")
    VehicleCategory.objects.filter(name__in=["Wedding Service", "Premium Cars"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_minimum_rental_days_vehicle_rental_mode_and_more'),
    ]

    operations = [
        migrations.RunPython(add_categories, remove_categories),
    ]
