# Generated by Django 5.0.1 on 2026-04-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_add_wedding_premium_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Mark as a premium/luxury vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_wedding_service',
            field=models.BooleanField(default=False, help_text='Available for wedding services'),
        ),
    ]
