# Generated by Django 6.0.4 on 2026-05-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_remove_wedding_premium_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, help_text='Material Symbols icon name', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pricing_unit', models.CharField(choices=[('per_day', 'Per Day'), ('per_trip', 'Per Trip')], default='per_day', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('state', models.CharField(default='Kerala', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hub', models.BooleanField(default=False, help_text='Major delivery hub city (shown first)')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['-is_hub', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeddingDecorationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='weddings/decorations/')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='included_km_per_day',
            field=models.PositiveIntegerField(default=200, help_text='Free kilometres included in the daily rate'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_chauffeur_available',
            field=models.BooleanField(default=False, help_text='Can be rented with a chauffeur'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='per_km_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Charge per km after the daily included kilometres are exhausted', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wedding_decoration_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default basic decoration charge for wedding service vehicles', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wedding_tier',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('premium', 'Premium'), ('iconic', 'Iconic')], help_text='Wedding tier — only used if is_wedding_service is true', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='with_driver_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily rate when rented with a chauffeur (overrides price_per_day if set)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='available_cities',
            field=models.ManyToManyField(blank=True, help_text='Cities where this vehicle can be picked up / delivered', related_name='vehicles', to='vehicles.city'),
        ),
    ]
