# Generated by Django 6.0.4 on 2026-05-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_bookingaddon_city_weddingdecorationpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description for search engines (150–160 chars)', max_length=300),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=300),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='meta_title',
            field=models.CharField(blank=True, help_text="Custom <title>; defaults to '{Brand} {Name} for Rent'", max_length=200),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description (150–160 chars)', max_length=300),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=300),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom <title> for this category page', max_length=200),
        ),
    ]
