# Generated by Django 6.0.4 on 2026-10-06 08:50

from django.db import migrations, models


def fill_coordinates(apps, schema_editor):
    from vehicles.geo import lookup
    City = apps.get_model("vehicles", "City")
    for city in City.objects.filter(latitude__isnull=True, longitude__isnull=True):
        coords = lookup(city.name)
        if coords:
            city.latitude, city.longitude = coords
            city.save(update_fields=["latitude", "longitude"])


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehicle_meta_description_vehicle_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Map pin; filled automatically for known Kerala towns', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.RunPython(fill_coordinates, migrations.RunPython.noop),
    ]
