# Generated by Django 6.0.4 on 2026-10-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_city_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wizard_step',
            field=models.PositiveSmallIntegerField(default=6, help_text='Furthest wizard step reached'),
        ),
    ]
