# Generated by Django 6.0.4 on 2026-10-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_wizard_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='show_in_hero',
            field=models.BooleanField(default=False, help_text='Showcase this vehicle in the home page hero slides (needs a photo)'),
        ),
    ]
