# Generated by Django 6.0.4 on 2026-10-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_vehicle_show_in_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('muv', 'MUV / MPV'), ('luxury', 'Luxury'), ('car', 'Car'), ('tempo', 'Tempo'), ('van', 'Van'), ('bus', 'Bus'), ('bike', 'Bike'), ('scooter', 'Scooter'), ('auto', 'Auto'), ('truck', 'Truck'), ('other', 'Other')], default='car', max_length=20),
        ),
    ]
