# Generated by Django 6.0.4 on 2026-10-10 04:04

from django.db import migrations, models


def clear_free_km(apps, schema_editor):
    # No vehicle includes free km; drop the old default of 200
    apps.get_model("vehicles", "Vehicle").objects.update(included_km_per_day=None)


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_vehicle_body_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='included_km_per_day',
            field=models.PositiveIntegerField(blank=True, help_text='Free kilometres included in the daily rate (leave empty if none)', null=True),
        ),
        migrations.RunPython(clear_free_km, migrations.RunPython.noop),
    ]
