# Generated by Django 6.0.4 on 2026-10-10 04:38

from django.db import migrations, models
from django.utils.text import slugify


def clean_slugs(apps, schema_editor):
    # Rebuild addresses like brand-model-brand-model-name without the repeats; keep the old one for a redirect
    Vehicle = apps.get_model("vehicles", "Vehicle")
    for v in Vehicle.objects.all():
        slug = slugify(v.name)
        for part in (v.model, v.brand):
            p = slugify(part or "")
            if p and p not in slug:
                slug = f"{p}-{slug}" if slug else p
        slug = slug or "vehicle"
        base, n = slug, 1
        while Vehicle.objects.filter(slug=slug).exclude(pk=v.pk).exists():
            slug, n = f"{base}-{n}", n + 1
        if slug != v.slug:
            Vehicle.objects.filter(pk=v.pk).update(previous_slug=v.slug, slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_free_km_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='previous_slug',
            field=models.SlugField(blank=True, help_text='Old web address, redirected to the current one', max_length=200),
        ),
        migrations.RunPython(clean_slugs, migrations.RunPython.noop),
    ]
