# Generated by Django 6.0.4 on 2026-10-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_vehicle_clean_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Tile photo for the home page; a cut-out PNG with a transparent background looks best', upload_to='categories/'),
        ),
    ]
