# Generated by Django 6.0.4 on 2026-10-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_category_tile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='has_ac',
            field=models.BooleanField(default=False, verbose_name='Air conditioning'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='luggage_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Large bags that fit in the boot', null=True),
        ),
    ]
