# Generated by Django 6.0.4 on 2026-10-11 04:41

from django.db import migrations, models


def luxury_type_to_flag(apps, schema_editor):
    """Luxury is now a separate switch, not a vehicle type."""
    Vehicle = apps.get_model("vehicles", "Vehicle")
    Vehicle.objects.filter(vehicle_type="luxury").update(vehicle_type="car", is_premium=True)


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_luggage_and_ac'),
    ]

    operations = [
        migrations.RunPython(luxury_type_to_flag, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vehicle',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Luxury vehicle: listed on the Premium page with a Premium badge', verbose_name='Luxury'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('muv', 'MUV / MPV'), ('car', 'Car'), ('tempo', 'Tempo'), ('van', 'Van'), ('bus', 'Bus'), ('bike', 'Bike'), ('scooter', 'Scooter'), ('auto', 'Auto'), ('truck', 'Truck'), ('other', 'Other')], default='car', max_length=20),
        ),
    ]
